version: '3.8'

services:
  frontend:
    image: miinning/vroom2go_frontend:latest
    build:
      context: .
      args:
        - VITE_API_URL=${BACKEND_URL:-http://localhost:5000}
        - VITE_SOCKET_URL=${BACKEND_URL:-http://localhost:5000}
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
    ports:
      - "80:80"
    restart: always
